/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroController;
import DAO.Conexao;
import DAO.UsuarioDAO;
import Model.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class CadastroView extends javax.swing.JFrame {

    private final CadastroController controller;

    /**
     * Creates new form Cadastro
     */
    
    public CadastroView() {
        initComponents();
        controller = new CadastroController(this);
        
            // Chama o método que adiciona um placeholder (texto de dica) no campo de texto do nome do usuário
    addPlaceholderToTextField(jTextField1Usuario, "Digite seu nome");

    // Chama o método que adiciona placeholder no campo de senha principal,
    // mostrando um texto cinza antes do usuário digitar algo
    addPlaceholderToPasswordField(jPasswordField1Senha, "Digite sua senha");

    // Chama o método que adiciona placeholder no campo de confirmação de senha,
    // também mostrando texto de dica antes do usuário digitar
    addPlaceholderToPasswordField(jPasswordField2Senha, "Confirme sua senha");
    }
    
        public void resetCamposComPlaceholder() {
        jTextField1Usuario.setText("Digite seu nome");
        jTextField1Usuario.setForeground(java.awt.Color.GRAY);

        jPasswordField1Senha.setEchoChar((char) 0);
        jPasswordField1Senha.setText("Digite sua senha");
        jPasswordField1Senha.setForeground(java.awt.Color.GRAY);

        jPasswordField2Senha.setEchoChar((char) 0);
        jPasswordField2Senha.setText("Confirme sua senha");
        jPasswordField2Senha.setForeground(java.awt.Color.GRAY);
    }
    
    private void addPlaceholderToTextField(JTextField textField, String placeholder) {
    textField.setText(placeholder);
    textField.setForeground(java.awt.Color.GRAY);

    textField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (textField.getText().equals(placeholder)) {
                textField.setText("");
                textField.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (textField.getText().isEmpty()) {
                textField.setText(placeholder);
                textField.setForeground(java.awt.Color.GRAY);
            }
        }
    });
}

private void addPlaceholderToPasswordField(JPasswordField passwordField, String placeholder) {
    passwordField.setEchoChar((char) 0); // mostra o texto do placeholder
    passwordField.setText(placeholder);
    passwordField.setForeground(java.awt.Color.GRAY);

    passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (String.valueOf(passwordField.getPassword()).equals(placeholder)) {
                passwordField.setText("");
                passwordField.setForeground(java.awt.Color.BLACK);
                passwordField.setEchoChar('•'); // volta a esconder a senha
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (String.valueOf(passwordField.getPassword()).isEmpty()) {
                passwordField.setEchoChar((char) 0); // mostra o texto do placeholder
                passwordField.setText(placeholder);
                passwordField.setForeground(java.awt.Color.GRAY);
            }
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1Usuario = new javax.swing.JTextField();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField2Senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/usuario/NetBeansProjects/Barbershop/src/main/java/View/Imagens/Cadastro_Fundo.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 416, 41));

        jPasswordField1Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 410, 40));

        jButton1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton1.setText("Cadastar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 420, -1));

        jButton2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 730, 420, 40));
        getContentPane().add(jPasswordField2Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 416, 40));

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/usuario/Projeto/NetBeansProjects/Barbershop/src/main/java/View/Imagens/caixa-login.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 700, 580));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("/home/usuario/Projeto/NetBeansProjects/Barbershop/src/main/java/View/Imagens/deixe a imagem em resolução Full HD (1920 x 1080)(1).png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 1030));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    controller.salvaUsuario();
  
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1SenhaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }
    

    public JPasswordField getjPasswordField1Senha() {
        return jPasswordField1Senha;
    }

    public void setjPasswordField1Senha(JPasswordField jPasswordField1Senha) {
        this.jPasswordField1Senha = jPasswordField1Senha;
    }

    public JPasswordField getjPasswordField2Senha() {
        return jPasswordField2Senha;
    }

    public void setjPasswordField2Senha(JPasswordField jPasswordField2Senha) {
        this.jPasswordField2Senha = jPasswordField2Senha;
    }

    public JTextField getjTextField1Usuario() {
        return jTextField1Usuario;
    }

    public void setjTextField1Usuario(JTextField jTextField1Usuario) {
        this.jTextField1Usuario = jTextField1Usuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JPasswordField jPasswordField2Senha;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1Usuario;
    // End of variables declaration//GEN-END:variables
}

