/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import DAO.Conexao;
import DAO.UsuarioDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;


    /**
     * Creates new form Login
     */
public Login() {
    initComponents();

    // Placeholder para o campo usuário
    TextUsuarioView.setText("Nome do usuário");
    TextUsuarioView.setForeground(java.awt.Color.GRAY);
    TextUsuarioView.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (TextUsuarioView.getText().equals("Nome do usuário")) {
                TextUsuarioView.setText("");
                TextUsuarioView.setForeground(java.awt.Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (TextUsuarioView.getText().isEmpty()) {
                TextUsuarioView.setForeground(java.awt.Color.GRAY);
                TextUsuarioView.setText("Nome do usuário");
            }
        }
    });

    // Placeholder para o campo senha
    TextSenhaView.setEchoChar((char) 0); // mostrar texto como está
    TextSenhaView.setText("Senha");
    TextSenhaView.setForeground(java.awt.Color.GRAY);
    TextSenhaView.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            String senha = new String(TextSenhaView.getPassword());
            if (senha.equals("Senha")) {
                TextSenhaView.setText("");
                TextSenhaView.setForeground(java.awt.Color.BLACK);
                TextSenhaView.setEchoChar('•'); // oculta senha
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            String senha = new String(TextSenhaView.getPassword());
            if (senha.isEmpty()) {
                TextSenhaView.setEchoChar((char) 0);
                TextSenhaView.setForeground(java.awt.Color.GRAY);
                TextSenhaView.setText("Senha"); // CORRIGIDO: com S maiúsculo
            }
        }
    });

    controller = new LoginController(this);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextSenhaView = new javax.swing.JPasswordField();
        TextUsuarioView = new javax.swing.JTextField();
        jButton2CadastrarView = new javax.swing.JButton();
        jButton1EntrarView = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextSenhaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSenhaViewActionPerformed(evt);
            }
        });
        getContentPane().add(TextSenhaView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 630, 50));

        TextUsuarioView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioViewActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuarioView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 630, 50));

        jButton2CadastrarView.setBackground(new java.awt.Color(153, 153, 153));
        jButton2CadastrarView.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton2CadastrarView.setText("Cadastrar");
        jButton2CadastrarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CadastrarViewActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2CadastrarView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 630, 50));

        jButton1EntrarView.setBackground(new java.awt.Color(153, 153, 153));
        jButton1EntrarView.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton1EntrarView.setText("Entrar");
        jButton1EntrarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EntrarViewActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1EntrarView, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 630, 50));

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/usuario/ProjetoBarbearia/NetBeansProjects/Barbershop/src/main/java/View/Imagens/Caixa_Fundo.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 730, 530));

        jLabelFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setIcon(new javax.swing.ImageIcon("/home/usuario/Projeto/NetBeansProjects/Barbershop/src/main/java/View/Imagens/deixe a imagem em resolução Full HD (1920 x 1080).png")); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -280, 1540, 1580));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioViewActionPerformed

    private void jButton1EntrarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EntrarViewActionPerformed
       
       controller.autenticar();




    }//GEN-LAST:event_jButton1EntrarViewActionPerformed

    private void TextSenhaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaViewActionPerformed

    private void jButton2CadastrarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CadastrarViewActionPerformed
        CadastroView cadastro = new CadastroView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton2CadastrarViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextSenhaView;
    private javax.swing.JTextField TextUsuarioView;
    private javax.swing.JButton jButton1EntrarView;
    private javax.swing.JButton jButton2CadastrarView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
    
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JPasswordField getTextSenha() {
        return TextSenhaView;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenhaView = TextSenha;
    }

    public JTextField getTextUsuario() {
        return TextUsuarioView;
    }

    public void setTextUsuario(JTextField TextUsuario) {
        this.TextUsuarioView = TextUsuario;
    }
    
}
