/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Conexao;
import DAO.UsuarioDAO;
import Model.Usuario;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalView() {
        initComponents();
        

    // Cria o painel com imagem
    PainelComImagem painelComImagem = new PainelComImagem("/View/Imagens/MenuAtualizado.jpeg");
    painelComImagem.setLayout(null); // layout absoluto para painel interno, se quiser posicionar algo dentro
    painelComImagem.setBounds(jPanel1.getBounds());

    // Remove o jPanel1 original e adiciona o painel com imagem, com constraints para layout absoluto
    getContentPane().remove(jPanel1);
    getContentPane().add(painelComImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(
        jPanel1.getX(), jPanel1.getY(), jPanel1.getWidth(), jPanel1.getHeight()
    ));

    // Agora adiciona os botões diretamente no getContentPane (fora do painel com imagem)
    // Para os botões ficarem sobre o painel, eles devem ser adicionados depois dele
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 780, 150, 30));
    getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 780, 180, 30));

    // Atualiza a variável jPanel1 para o novo painel com imagem
    jPanel1 = painelComImagem;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        CadastroServiço = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Cadastrar-se");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setText("Agende já");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuCadastro.setText("Menu");

        CadastroCliente.setIcon(new javax.swing.ImageIcon("/home/usuario/ProjetoBarbearia/NetBeansProjects/Barbershop/src/main/java/View/Imagens/Icons/IconClient24.png")); // NOI18N
        CadastroCliente.setText("Cadastrar");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(CadastroCliente);

        CadastroServiço.setIcon(new javax.swing.ImageIcon("/home/usuario/ProjetoBarbearia/NetBeansProjects/Barbershop/src/main/java/View/Imagens/Icons/IconService.png")); // NOI18N
        CadastroServiço.setText("Agendamento");
        CadastroServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroServiçoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(CadastroServiço);

        jMenuBar1.add(jMenuCadastro);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        CadastroView cadastro = new CadastroView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroServiçoActionPerformed
        AgendamentoView agendamento = new AgendamentoView();
        agendamento.setVisible(true);
    }//GEN-LAST:event_CadastroServiçoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgendamentoView agendamento = new AgendamentoView();
        agendamento.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadastroView cadastro = new CadastroView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroServiço;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
